/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    About: typeof import('./src/components/pages/about.vue')['default']
    Card: typeof import('./src/components/middleware/card.vue')['default']
    Countdown: typeof import('./src/components/middleware/countdown.vue')['default']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    Header: typeof import('./src/components/header/header.vue')['default']
    Home: typeof import('./src/components/pages/home.vue')['default']
    Random: typeof import('./src/components/pages/random.vue')['default']
    RandomFake: typeof import('./src/components/pages/random-fake.vue')['default']
    RandomReal: typeof import('./src/components/pages/random-real.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Settings: typeof import('./src/components/pages/settings.vue')['default']
    User_info_view: typeof import('./src/components/middleware/user_info_view.vue')['default']
  }
}
