name: Deploy
run-name: ${{ github.actor }} deployed electron app
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, '[deploy]')
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install
      
      - name: Build for windows and linux
        run:  bun run build:win

      - name: test
        run: ls release

