name: Deploy
run-name: ${{ github.actor }} deployed electron app
on: 
  push:
    branches:
      - main
    tags:
      - 'v**.**.**'
jobs:
  deploy:
    runs-on: ${{ matrix.os }}
    if: contains(github.event.head_commit.message, '[deploy]')
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm, windows-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - uses: actions/cache@v4
        with:
          key: ${{ runner.os}}-bun-${{ hashFiles('**/bun.lockb') }}
          path: node_modules

      - name: Install dependencies
        run: bun install
      
      - name: Build and Release
        run:  bun run dist
        env:
          GH_TOKEN: ${{ secrets.CUSTOM_TOKEN }}


