name: Deploy
run-name: ${{ github.actor }} deployed electron app
on:
  push:
    tags:
      - 'v*'
jobs:
  deploy:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - uses: actions/cache@v4
        with:
          key: ${{ runner.os}}-bun-${{ hashFiles('**/bun.lockb') }}
          path: node_modules

      - name: Install dependencies
        run: bun install
      
      - name: Build for windows and linux
        run:  bun run build
        env:
          GH_TOKEN: ${{ secrets.CUSTOM_TOKEN }}

      - name: upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}
          path: dist
            
      - name: release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            "release/v**/**.exe"
            "release/v**/**.appimage"
        env:
          GITHUB_TOKEN: ${{ secrets.CUSTOM_TOKEN }}

